environment:
  MAPNIK_GIT: 3.0.1-4-ga78a895
  node_pre_gyp_accessKeyId:
    secure: 7DrSVc5eIGtmMcki5H+iRft+Tk3MJTwDBQEUuJHWaQ4=
  node_pre_gyp_secretAccessKey:
    secure: 1amwJJw9fu0j6dXnc5KsAQbSYf7Cjw/dapT6OZWABa6nc52grkKeLQ+DGaOfQz8i
  matrix:
    # custom visual studio 2014 builds
    - nodejs_version: 0.10.36
      platform: x64
      msvs_toolset: 14
      TOOLSET_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140
#    - nodejs_version: 0.10.36
#      platform: x86
#      msvs_toolset: 14
#      TOOLSET_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140
#    - nodejs_version: 0.12.2
#      platform: x86
#      msvs_toolset: 14
#      TOOLSET_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140
    - nodejs_version: 0.12.2
      platform: x64
      msvs_toolset: 14
      TOOLSET_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140

os: Visual Studio 2015

shallow_clone: true

install:
#try to workaround https://github.com/mapnik/node-mapnik/issues/487
#http://www.appveyor.com/docs/lang/nodejs-iojs
  - ps: Install-Product node $env:nodejs_version $env:platform
  - scripts\build-appveyor.bat

build: off
test: off
deploy: off
