version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

# environment variables
#environment:
  # my_var1: value1
  # my_var2: value2
  # this is how to set encrypted variable. Go to "Encrypt data" page in account menu to encrypt data.
  #node_pre_gyp_accessKeyId:
  #  secure: gX0sHZ0FHmCAPWH7zuKEi7J1jIMdPEk5DzO38SgGKa4=
  #node_pre_gyp_secretAccessKey:
  #  secure: TGX9/Wb26kCr4QPh2PPVbNp/ZW1JaFugEzcnULXfB7xMO5rnH5shXpPvOZxgMNqV


# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - scripts\build_against_sdk_00-START-HERE.bat
  # to run script as a PowerShell command prepend it with ps:
  # batch commands start from cmd:

