environment:
  node_pre_gyp_accessKeyId:
    secure: T1Pel/pv9SVfiVvZW8TLZnvZX6M4HQTiR7LUZnF1tuY=
  node_pre_gyp_secretAccessKey:
    secure: 8f5eTxMHpuVGHon2wbqrZuq3wzQfEuXMCcOyafBLza0T2VIOoBjbjDbgRbyRIzsT
  matrix:
  - nodejs_version: 0.10.33
    platform: x86
    msvs_toolset: 14
    BUILD_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140
  - nodejs_version: 0.10.33
    platform: x64
    msvs_toolset: 14
    BUILD_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140
  - nodejs_version: 0.11.14
    platform: x86
    msvs_toolset: 14
    BUILD_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140
  - nodejs_version: 0.11.14
    platform: x64
    msvs_toolset: 14
    BUILD_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140

os: Visual Studio 2014 CTP4

shallow_clone: true

install:
  - SET PATH=C:\Program Files\7-Zip;%PATH%
  - SET PATH=c:\Python27;%PATH%
  - ps: Write-Output "fetching mapnik sdk"
  - ps: Start-FileDownload https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-$env:msvs_toolset.0-$env:Platform-v3.0.0-rc1-57-g2577a6c.7z -FileName mapnik-sdk.7z
  - ps: Write-Output "extracting mapnik sdk"
  - ps: invoke-expression "& 7z -y x mapnik-sdk.7z | FIND /V `"ing  `""

build: off
test: off
deploy: off