environment:
  node_pre_gyp_accessKeyId:
    secure: T1Pel/pv9SVfiVvZW8TLZnvZX6M4HQTiR7LUZnF1tuY=
  node_pre_gyp_secretAccessKey:
    secure: 8f5eTxMHpuVGHon2wbqrZuq3wzQfEuXMCcOyafBLza0T2VIOoBjbjDbgRbyRIzsT
  matrix:
  - nodejs_version: "0.10"
  - nodejs_version: "0.11.13"

platform:
  - x86
  - x64

shallow_clone: true

install:
  # http://help.appveyor.com/discussions/problems/618-nodejs-10030-doesnt-work-on-appveyor-cant-find-npm#comment_34002825
  - ps: Install-Product node $env:nodejs_version $env:Platform
  # install 2014 c++ runtime
  - ps: Start-FileDownload "https://mapnik.s3.amazonaws.com/dist/dev/VS-2014-runtime/vcredist_$env:Platform.exe"
  - .\vcredist_%platform%.exe /q /norestart
  - npm install
  - npm test || true

build: off
test: off
deploy: off