environment:
  node_pre_gyp_accessKeyId:
    secure: T1Pel/pv9SVfiVvZW8TLZnvZX6M4HQTiR7LUZnF1tuY=
  node_pre_gyp_secretAccessKey:
    secure: 8f5eTxMHpuVGHon2wbqrZuq3wzQfEuXMCcOyafBLza0T2VIOoBjbjDbgRbyRIzsT
  matrix:
#  - nodejs_version: 0.11.14
#    platform: x86
#    msvs_toolset: 14
#    BUILD_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140
  - nodejs_version: 0.11.14
    platform: x64
    msvs_toolset: 14
    BUILD_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140
#  - nodejs_version: 0.10.33
#    platform: x86
#    msvs_toolset: 14
#    BUILD_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140
#  - nodejs_version: 0.10.33
#    platform: x64
#    msvs_toolset: 14
#    BUILD_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140

os: Visual Studio 2014 CTP4

shallow_clone: true

install:
  # find and remove default node.exe to avoid conflicts
  # node: we will still rely on default installed npm (should work)
  - node -e "console.log(process.execPath)" > node_path.txt
  - SET /p NODE_EXE_PATH=<node_path.txt
  - del node_path.txt
  - del /q /s "%NODE_EXE_PATH%"
  # add local node to path (since we install it below)
  - SET PATH=%CD%;%PATH%;
  # call VS Command Prompt AFTER DOWNLOADS (require lowercase platform)
  # VS command prompt will override %PLATFORM% to upper case!!!
  # %PLATFORM% will go from x64 to X64
  - SET PATH=C:\Program Files (x86)\MSBuild\%msvs_toolset%.0\bin;%PATH%
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio %msvs_toolset%.0\VC\bin;%PATH%
  # use 64 bit python if platform is 64 bit
  - if "%PLATFORM%" == "x64" set PATH=C:\Python27-x64;%PATH%
  - SET PATH=C:\Program Files\7-Zip;%PATH%
  - SET ARCHPATH=
  - if %platform% == x64 (SET ARCHPATH=x64/)
  - ps: Write-Output "fetching mapnik sdk https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-$env:msvs_toolset.0-$env:Platform-v3.0.0-rc1-57-g2577a6c.7z"
  - ps: Start-FileDownload https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-$env:msvs_toolset.0-$env:Platform-v3.0.0-rc1-57-g2577a6c.7z -FileName mapnik-sdk.7z
  - ps: Write-Output "extracting mapnik sdk"
  - ps: invoke-expression "& 7z -y x mapnik-sdk.7z | FIND /V `"ing  `""
  # install node version per visual studio toolset
  - ps: Write-Output "fetching https://mapbox.s3.amazonaws.com/node-cpp11/v$env:nodejs_version/${env:ARCHPATH}node.exe"
  - ps: Start-FileDownload "https://mapbox.s3.amazonaws.com/node-cpp11/v$env:nodejs_version/${env:ARCHPATH}node.exe"
  # clear out node-gyp header cache
  - if "%msvs_toolset%" == "14" rd /s /q %USERPROFILE%\.node-gyp
  # add local node-pre-gyp dir to path
  - SET PATH=node_modules\.bin;%PATH%
  # call VS Command Prompt AFTER DOWNLOADS, will override %PLATFORM% to upper case!!!
  - if %platform% == x64 CALL "C:\Program Files (x86)\Microsoft Visual Studio %msvs_toolset%.0\VC\vcvarsall.bat" amd64
  - if %platform% == x86 CALL "C:\Program Files (x86)\Microsoft Visual Studio %msvs_toolset%.0\VC\vcvarsall.bat" amd64_x86
  - node -v
  - node -e "console.log(process.arch,process.execPath)"
  - SET MAPNIK_SDK=%CD%\mapnik-sdk
  - SET PATH=%MAPNIK_SDK%\bin;%MAPNIK_SDK%\libs;%PATH%
  - SET PROJ_LIB=%MAPNIK_SDK%\share\proj
  - SET GDAL_DATA=%MAPNIK_SDK%\share\gdal
  - SET ICU_DATA=%MAPNIK_SDK%\share\icu
  - npm install --build-from-source --msvs_version=2013 %BUILD_ARGS% --loglevel=http
  # TODO copy libs
  - npm test
  - node-pre-gyp package %BUILD_ARGS%
  - ps: if($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains('[publish binary]')) { node-pre-gyp --msvs_version=2013 publish %BUILD_ARGS% }

build: off
test: off
deploy: off