version: 1.0.{build}

clone_folder: c:\dev2\node-mapnik

environment:
  node_pre_gyp_accessKeyId:
    secure: 9JxHOXxgQ7UaXFCQh4ihEBDElQgE4l0XareRstBCpLk=
  node_pre_gyp_secretAccessKey:
    secure: s1us6xb8U2EqlaVYtoVMtulfgMdX4VVEKgTF+Eft104gWja1GG0Blf6cMJtG7Yu3
  matrix:
  - nodejs_version: 0.10
  - nodejs_version: 0.11

platform:
#  - x64
  - x86

matrix:
  allow_failures:
    - platform: x86
      nodejs_version: 0.10
    - platform: x86
      nodejs_version: 0.11

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node -e "console.log('node version ' + process.version + ' architecture ' + process.arch);"
  - node --version
  - npm --version
  # upgrade node-gyp to ensure it knows about msvs 2013
  - npm install node-gyp
  - scripts\build_against_sdk_00-START-HERE.bat
  - npm test
  - node-pre-gyp package
  - SET CM=%APPVEYOR_REPO_COMMIT_MESSAGE%
  - ECHO commit message %CM%
  - if not "%CM%" == "%CM:[publish binary]=%" node-pre-gyp publish

build: off
test: off
deploy: off