environment:
  node_pre_gyp_accessKeyId:
    secure: T1Pel/pv9SVfiVvZW8TLZnvZX6M4HQTiR7LUZnF1tuY=
  node_pre_gyp_secretAccessKey:
    secure: 8f5eTxMHpuVGHon2wbqrZuq3wzQfEuXMCcOyafBLza0T2VIOoBjbjDbgRbyRIzsT
  matrix:
  - nodejs_version: "0.10"
  - nodejs_version: "0.11"

platform:
  #- x86
  - x64

shallow_clone: true

install:
  # http://help.appveyor.com/discussions/problems/618-nodejs-10030-doesnt-work-on-appveyor-cant-find-npm#comment_34002825
  - ps: Install-Product node $env:nodejs_version $env:Platform
  # install 2014 c++ runtime
  - ps: Start-FileDownload "https://mapnik.s3.amazonaws.com/dist/dev/VS-2014-runtime/vcredist_$env:Platform.exe"
  - .\vcredist_%platform%.exe /q /norestart
  - npm install
  - node_modules\.bin\node-pre-gyp reveal module --silent > module.txt
  - SET /p MODULE=<module.txt
  - del module.txt
  # put 64 bit python on PATH / http://www.appveyor.com/docs/installed-software
  - if "%PLATFORM%" == "x64" set PATH=C:\Python27-x64;%PATH%
  - python -c "import platform;print(platform.architecture())"
  - python -c "import ctypes,os;print('%MODULE%');print os.path.exists('%MODULE%');ctypes.CDLL('%MODULE%')" || true
  - npm test || true

build: off
test: off
deploy: off