name: Node.js Package

on:
  release:
    types: [created]

env:
  VCPKG_SHA: 291b84e651bc21d90088394139097f9a5396cc00
  NUGET_REGISTRY: https://nuget.pkg.github.com/mathisloge/index.json
  NUGET_USERNAME: mathisloge
  VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"
  VCPKG_NUGET_REPOSITORY: https://github.com/mathisloge/vcpkg-nuget.git
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            architecture: x64
            node_version: 16

          - os: ubuntu-latest
            mono: mono
            architecture: x64
            node_version: 16

          #- os: macos-latest
          #  mono: mono
          #  architecture: x64
          #  node_version: 16

    permissions:
      contents: read
      packages: write

    steps:
      - uses: ilammy/msvc-dev-cmd@v1

      - uses: actions/checkout@v2

      - name: checkout vcpkg
        uses: actions/checkout@v2
        with:
          repository: "microsoft/vcpkg"
          ref: ${{ env.VCPKG_SHA }}
          path: vcpkg

      - name: "Setup vcpkg"
        shell: bash
        run: ./vcpkg/bootstrap-vcpkg.sh

      - name: "Setup NuGet Credentials"
        shell: "bash"
        run: >
          ${{ matrix.mono }} `./vcpkg/vcpkg fetch nuget | tail -n 1`
          sources add
          -source "${{ env.NUGET_REGISTRY }}"
          -storepasswordincleartext
          -name "GitHub"
          -username "${{ env.NUGET_USERNAME }}"
          -password "${{ secrets.NUGET_REGISTRY_PAT }}"

      - name: "Setup NuGet apikey"
        shell: "bash"
        run: >
          ${{ matrix.mono }} `./vcpkg/vcpkg fetch nuget | tail -n 1`
          setapikey "${{ secrets.NUGET_REGISTRY_PAT }}" -Source "${{ env.NUGET_REGISTRY }}"

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          registry-url: 'https://registry.npmjs.org'

      - run: npm install
      #- run: npm test

      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_PAT}}
          NODE_PRE_GYP_GITHUB_TOKEN: ${{secrets.NUGET_REGISTRY_PAT}}
